# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: github-actions # See documentation for possible values
    directory: / # Location of package manifests
    rebase-strategy: auto
    target-branch: main
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"

  # Python dependencies (pip ecosystem for uv projects)
  - package-ecosystem: pip
    directory: /
    rebase-strategy: auto
    target-branch: main
    schedule: # dependabot does not support cron
      interval: monthly
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 3
    groups:
      python-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - uv-demo* # Exclude the local package itself
  
  # Docker - Devcontainers
  - package-ecosystem: "devcontainers"
    directory: /
    rebase-strategy: auto
    target-branch: main
    schedule:
      interval: monthly
      time: "08:00"
      timezone: Europe/Oslo

# TODO: Check if adding Docker ecosystem would be smart.
