version: '3'

vars:
  PROJECT_NAME: uv-demo
  PYTHON_VERSION: '>=3.12'

tasks:
  # Setup and Installation
  install:
    desc: Install dependencies and setup development environment
    cmds:
    - uv sync --dev
    - task: install-hooks

  install-hooks:
    desc: Install pre-commit hooks
    cmds:
    - uv run pre-commit install
    status:
    - test -f .git/hooks/pre-commit

  # Code Quality
  pre-commit:
    desc: Run pre-commit hooks on all files
    cmds:
    - uv run pre-commit run --all-files

  check:
    desc: Run all code quality checks
    deps: [lint, typecheck, test-cov, deps-check]

  format:
    desc: Format code with Ruff
    cmds:
    - uv run ruff format

  lint:
    desc: Run linting checks
    cmds:
    - uv run ruff check

  lint-fix:
    desc: Run linting checks and auto-fix issues
    cmds:
    - uv run ruff check --fix

  typecheck:
    desc: Run type checking with mypy
    cmds:
    - uv run mypy src/

  deps-check:
    desc: Check for dependency issues
    cmds:
    - uv run deptry .

  # Testing
  test:
    desc: Run tests
    cmds:
    - uv run pytest

  test-cov:
    desc: Run tests with coverage
    cmds:
    - uv run pytest --cov

  # Security
  security:
    desc: Run security scans
    deps: [security-workflows]

  # RECOMMENDED: Run Safety in GHA only, auth is set up on the github repo.
  # Uncomment the following task to enable local safety checks.
  # security-deps:
  #  desc: Scan for dependency vulnerabilities
  #  cmds:
  #  - uv run safety scan
  #  ignore_error: true

  # RECOMMENDED: Scan Zizmor locally before running in GHA to catch potential issues early.
  security-workflows:
    desc: Audit GitHub Actions workflows
    cmds:
    - uv run zizmor .github/workflows/
    ignore_error: true

  # Build and Release
  build:
    desc: Build the package
    cmds:
    - uv build
    - echo "Package built in dist/"

  clean:
    desc: Clean build artifacts and caches
    cmds:
    - rm -rf dist/ build/ *.egg-info/
    - rm -rf .pytest_cache/ .mypy_cache/ .ruff_cache/
    - rm -rf htmlcov/ .coverage coverage.xml
    - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

  # Development
  run:
    desc: Run the CLI application
    cmds:
    - uv run --no-sync {{.PROJECT_NAME}}

  dev-setup:
    desc: Complete development environment setup
    deps: [install, check]
    cmds:
    - echo "Development environment ready!"
    - echo "Try - task run"

  # Version Management
  tag:
    desc: 'Create and push a new version tag (usage: task tag VERSION=v1.0.0)'
    cmds:
    - git tag {{.VERSION}}
    - git push origin {{.VERSION}}
    - echo "Tagged and pushed {{.VERSION}}"
    requires:
      vars: [VERSION]

  # CI/CD Simulation
  ci-local:
    desc: Simulate CI pipeline locally
    deps: [pre-commit, test-cov, security]
    cmds:
    - echo "Local CI simulation complete!"

  # Help
  default:
    desc: Show available tasks
    cmds:
    - task --list-all

  help:
    desc: Show detailed help for common workflows
    cmds:
    - |
      echo "Common workflows:"
      echo ""
      echo "  Development setup:"
      echo "    task dev-setup    # Complete setup"
      echo "    task install      # Install dependencies only"
      echo ""
      echo "  Code quality:"
      echo "    task check        # Run all quality checks"
      echo "    task format       # Format code"
      echo "    task lint-fix     # Fix linting issues"
      echo ""
      echo "  Testing:"
      echo "    task test         # Run tests"
      echo ""
      echo "  Release:"
      echo "    task build        # Build package"
      echo "    task tag VERSION=v1.0.0  # Create release tag"
      echo ""
      echo "  Use 'task --list' to see all available tasks"
