FROM ghcr.io/ac-willeke/uv-demo:latest

# Install git only in the devcontainer, not in prod images
# TODO add from features using devcontainer.json instead of here
# RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
