version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    # https://docs.astral.sh/uv/guides/integration/docker/#developing-in-a-container
    volumes:
    - ..:/workspaces:cached   # Bind mount: sync project files
    - /workspaces/uv-demo/.venv   # Anonymous volume: ensure .venv is not overwritten by bind mount
    - uv-cache:/root/.cache/uv   # Named volume: persist UV cache between container restarts

    # Override the default command to keep the container running
    command: sleep infinity

# Named volumes
volumes:
  uv-cache:
