name: CI | Docker Build and Test
# TODO: remove multistage/standalone 

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.ref_name }}-${{
    github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: "build image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: uv-demo:latest
          cache-from: type=gha,scope=uv-demo
          cache-to: type=gha,mode=min,scope=uv-demo
          outputs: type=docker,dest=/tmp/uv-demo.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: uv-demo
          path: /tmp/uv-demo.tar

  test:
    name: "test image"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: uv-demo
          path: /tmp
  
      - name: Load images
        run: |
          docker load --input /tmp/uv-demo.tar
          docker image ls -a

      - name: Test command line
        run: python --version

      - name: Test Docker compose
        run: |
          docker compose up -d
          docker compose down
