name: CI | Python Quality, Build and Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    name: Code Quality (pre-commit)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
      with:
        persist-credentials: false
    - uses: tox-dev/action-pre-commit-uv@246b66536e366bb885f52d61983bf32f7c95e8b1   # v1.0.3

  test-and-analysis:
    name: Tests, Coverage & Dependency Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d   # v7.1.0
      with:
        enable-cache: true

          # TODO: add separate group for ci in .toml
    - name: Install dependencies
      run: uv sync --group dev

    - name: Show Git tag
      run: |
        echo "Git describe: $(git describe --tags --dirty --always)"
        uv run python -c "import uv_demo; print(f'Package version: {uv_demo.__version__}')"

    - name: Run deptry (dependency check)
      run: uv run deptry . --known-first-party uv_demo

    - name: Run tests with coverage
      run: uv run pytest -m "not ci_exclude"

        # Requires CODECOV account from codecov.io
        # add CODECOV_TOKEN to GitHub repo secrets
    - name: Upload coverage to Codecov
      if: github.event.repository.private == false
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7   # v5.5.1
      with:
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-and-inspect:
    name: Build & Inspect Package
    needs: [code-quality, test-and-analysis]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
      with:
        fetch-depth: 0   # Required for setuptools-scm
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516   # v2.14.0
